version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
